### ISSUE TITLE
关于论文两处公式的一些疑问？

### ISSUE THREAD

**Issue by cingtiye** [thu-coai/Emotional-Support-Conversation#13]
你好，非常期待作者开源代码~
这里在读论文的时候，发现两个公式中的变量似乎没有在论文中解释：
1）：$h_{1,1}^s$表示什么意思？${\hat{H}}^s$是把这些$h^s_{i,j}$一起concat吗？
![image](https://user-images.githubusercontent.com/32251546/172632125-b1aafa7e-ce74-4d52-8ba6-1293aa166242.png)
2）：$C_1$表示的什么意思？
![image](https://user-images.githubusercontent.com/32251546/172633482-567733f5-aa7d-41e8-921c-87f9dc3db9c8.png)

非常期望得到作者的回复~
谢谢~

**Comment by lsy641** [comment]
It seems the content is not from our paper
