### ISSUE TITLE
a question about the backbone models

### ISSUE THREAD

**Issue by BaiMeiyingxue** [thu-coai/Emotional-Support-Conversation#16]
Hi,

Great work!
I was wondering whether it is possible to change the English task into a Chinese task.
Do you think it is possible to make the strategy come true through the Chinese data and the Chinese model?

Thanks for your reply!

**Comment by chujiezheng** [comment]
I think the strategies still work but you may need to manually annotate Chinese dialogue utterances using our strategy schema.

**Comment by BaiMeiyingxue** [comment]
got it, thank you!

**Comment by chujiezheng** [comment]
BTW, you can refer to our other paper [PsyQA](https://aclanthology.org/2021.findings-acl.130/). It proposes a Chinese long-text counseling dataset and adopts a similar strategy schema. Hope this helps.

**Comment by BaiMeiyingxue** [comment]
> BTW, you can refer to our other paper [PsyQA](https://aclanthology.org/2021.findings-acl.130/). It proposes a Chinese long-text counseling dataset and adopts a similar strategy schema. Hope this helps.
sorry, i just got the message,
i'm glad to find the paper!

**Comment by BaiMeiyingxue** [comment]
may i ask for you some detail about the nlp technology?
if i wanna realize the ESC language model based on Chinese,  in addition to the training data, what other parts of the code do I need to change? could i just use the original pretrained model and parameters?
Looking forward to your reply!

**Comment by chujiezheng** [comment]
You should instead use a Chinese pre-trained dialogue model. Unfortunately, I did not see a direct alternative for BlenderBot (e.g., a huggingface checkpoint) and you should build your own pipeline for data processing and model training.

**Comment by BaiMeiyingxue** [comment]
i got it~ 
about the paper PsyQA,  could i get the source code?

**Comment by chujiezheng** [comment]
Please follow its repo's README: https://github.com/thu-coai/PsyQA

**Comment by BaiMeiyingxue** [comment]
ok, thank you for your answer!

**Comment by BaiMeiyingxue** [comment]
> You should instead use a Chinese pre-trained dialogue model. Unfortunately, I did not see a direct alternative for BlenderBot (e.g., a huggingface checkpoint) and you should build your own pipeline for data processing and model training.

BTW, if we wanna pick one pretrained model, what condition should we think about since we find the Chinese pretrained model[https://github.com/thu-coai/CDial-GPT](url). Whether it can be used?

**Comment by chujiezheng** [comment]
CDial-GPT is OK but may not be satisfactory. You can consider our released [EVA 2.0](https://github.com/thu-coai/EVA). It is one of the most powerful Chinese dialogue models open-sourced so far (while there are only a few open-sourced Chinese dialogue models :) ).

**Comment by BaiMeiyingxue** [comment]
> CDial-GPT is OK but may not be satisfactory. You can consider our released [EVA 2.0](https://github.com/thu-coai/EVA). It is one of the most powerful Chinese dialogue models open-sourced so far (while there are only a few open-sourced Chinese dialogue models :) ).

thanks for your effort~
