### ISSUE TITLE
interact_issue

### ISSUE THREAD

**Issue by xielaobanyy** [thu-coai/Emotional-Support-Conversation#17]
Hello, I recently encountered a problem in replicating your code. I tried to train the model _strat with strategies, but there was some problem in the final interact process. Do you ever encounter it? Looking forward to your reply!
![bug](https://user-images.githubusercontent.com/92131703/201817512-6197aec9-33c6-4b82-bbfe-ae21793df95b.png)

**Comment by chujiezheng** [comment]
You can refer to the modified code here: https://github.com/thu-coai/Emotional-Support-Conversation/issues/11#issuecomment-1020719715

**Comment by xielaobanyy** [comment]
Thank you for your reply, the problem has been solved
