### ISSUE TITLE
运行interact_strat.sh时，一直提示KeyError: 'strategy'。请求解决谢谢

### ISSUE THREAD

**Issue by caoyaru123** [thu-coai/Emotional-Support-Conversation#18]
错误如下：
用户无论输入什么，机器都提示策略错误。是找不到策略吗？求作者解答 谢谢
A new conversation starts!
Human: hi
Traceback (most recent call last):
  File "/root/Emotional-Support-Conversation-main/codes_zcj/interact.py", line 168, in <module>
    inputs = inputter.convert_data_to_inputs(history, toker, **dataloader_kwargs)
  File "/root/Emotional-Support-Conversation-main/codes_zcj/inputters/strat.py", line 87, in convert_data_to_inputs
    strat_id = process('[' + dialog[i]['strategy'] + ']')
KeyError: 'strategy'

**Comment by chujiezheng** [comment]
可以参见这个issue：https://github.com/thu-coai/Emotional-Support-Conversation/issues/11

**Comment by caoyaru123** [comment]
参照11修复了代码，现在又提醒KeyError: tensor(0)。麻烦作者指导一下，谢谢您
![image](https://user-images.githubusercontent.com/121163561/210370915-949d98a3-ab26-444a-8197-ab781d086b1e.png)

**Comment by chujiezheng** [comment]
你这里的strat_id_out是tensor，得转化为int

**Comment by caoyaru123** [comment]
应该怎么写呀，能麻烦写一下吗，我写的还是提示不对，谢谢了

**Comment by chujiezheng** [comment]
strat_id_out.item()

**Comment by caoyaru123** [comment]
非常感谢
