### ISSUE TITLE
在inteact_strat.sh一直提醒 command not found

### ISSUE THREAD

**Issue by caoyaru123** [thu-coai/Emotional-Support-Conversation#20]
一直提醒--fp16 false 下一句的参数名称 command not found。谁在-fp16 false 下面就提醒谁找不到，麻烦作者指导一下，谢谢
![image](https://user-images.githubusercontent.com/121163561/210364801-178cf689-3fd8-427a-9cda-b4553a72ff26.png)
![image](https://user-images.githubusercontent.com/121163561/210364877-3f18b26b-cb39-4b87-b936-fd6cb3752f3b.png)

**Comment by chujiezheng** [comment]
--fp16 false \ 这一行最后不要留空格

**Comment by caoyaru123** [comment]
又显示无法识别这两个参数。我看interact.py确实没有这两个参数名称，该怎么修改
interact.py: error: unrecognized arguments: --max_src_len 150 --max_tgt_len 50

**Comment by chujiezheng** [comment]
参见https://github.com/thu-coai/Emotional-Support-Conversation/issues/15#issuecomment-1300678763
