### ISSUE TITLE
有预训练的DialoGPT-small 模型么，发个链接呗

### ISSUE THREAD

**Issue by AlbertBJ** [thu-coai/Emotional-Support-Conversation#23]

**Comment by chujiezheng** [comment]
我没有存。你可以使用我们在huggingface hub上发布的blender模型

AlbertBJ ***@***.***>于2023年1月11日 周三19:59写道：

**Comment by AlbertBJ** [comment]
facebook/blenderbot-3B 我看 这个上面写的  open-domain chatbot， 这个 使用 emotion数据了么？还是 说 我需要ft这个blenderbot-3B 的模型，facebook/blenderbot_small-90M 我看也是写的开放域？

**Comment by chujiezheng** [comment]
我们发布的是这个：https://huggingface.co/thu-coai/blenderbot-400M-esconv

**Comment by AlbertBJ** [comment]
好嘞，谢谢；

**Comment by AlbertBJ** [comment]
我看readme中 [BlenderBot-small](https://huggingface.co/facebook/blenderbot_small-90M)  指向的是 facebook的地址？？

**Comment by chujiezheng** [comment]
我们发布的是已经微调过的400M blender，readme是实验中使用的微调前的90M blender

**Comment by AlbertBJ** [comment]
👌
