### ISSUE TITLE
关于策略识别与生成的问题

### ISSUE THREAD

**Issue by caoyaru123** [thu-coai/Emotional-Support-Conversation#25]
作者您好，不好意思打扰一下：可以问一下关于策略如何根据历史文本识别的吗？，以及如何根据已经识别出策略， 如何生成相应的回复文本的？
我修改了8个策略的编号。重新从头训练推理，生成的结果中 策略则不准确了。所以不太清楚是如何根据对话历史识别出策略的。
关于第二个问题：根据对话历史和策略生成response内容。根据文章得知 response内容应该不是根据策略分类匹配的内容，那应该是如何生成的? 在哪个代码文件里可以找到？

对您的研究非常感兴趣，麻烦作者可以帮忙解答一下，十分感谢

**Comment by Ashtray4** [comment]
可以一起讨论吗

**Comment by caoyaru123** [comment]
可以的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月27日(周四) 中午11:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [thu-coai/Emotional-Support-Conversation] 关于策略识别与生成的问题 (Issue #25)




 
可以一起讨论吗

**Comment by Ashtray4** [comment]
我的qq1034579793，方便加qq沟通交流吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月27日(周四) 中午11:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [thu-coai/Emotional-Support-Conversation] 关于策略识别与生成的问题 (Issue #25)




 可以的 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2023年4月27日(周四) 中午11:44 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [thu-coai/Emotional-Support-Conversation] 关于策略识别与生成的问题 (Issue #25) 
 
 
 
 
   
 可以一起讨论吗
