### ISSUE TITLE
”glove.6B.300d.model.bin“ 文件缺失

### ISSUE THREAD

**Issue by wlr737** [thu-coai/Emotional-Support-Conversation#27]
./codes_zcj/metric/word2vec/evaluate.py 中第15行中：
class Embedding(object):
    def __init__(self):
        path = '/home/zhengchujie/wordvector/english/glove6B' # please modify the path manually
        # path = ''
        self.m = KeyedVectors.load(os.path.join(path, 'glove.6B.300d.model.bin'), mmap='r')
        try:
            self.unk = self.m.vectors.mean(axis=0)
        except AttributeError:
            self.unk = self.m.syn0.mean(axis=0)

'glove.6B.300d.model.bin'文件要怎么下载呢

**Comment by Ashtray4** [comment]
https://onedrive.live.com/?authkey=%21AM6UkpxAQnqqtaY&id=750C6D59C3BFBC4C%215438&cid=750C6D59C3BFBC4C
