### ISSUE TITLE
运行bash RUN/infer_vanilla.sh报错

### ISSUE THREAD

**Issue by Spebb** [thu-coai/Emotional-Support-Conversation#29]
您好！
我在运行bash RUN/infer_vanilla.sh报以下错误：
![1](https://user-images.githubusercontent.com/126932939/236257194-39b04c31-3bf8-474f-af94-db972df04e4a.jpg)
这是由于以下代码
![image](https://user-images.githubusercontent.com/126932939/236257512-8c3d292f-6471-496e-9530-35ffea108186.png)
请问怎么修改呢？

**Comment by chujiezheng** [comment]
检查下路径，看起来像是你的bash脚本里no_repeat_ngram_size参数后没有留空格

**Comment by Spebb** [comment]
非常感谢，已正常运行
