### ISSUE TITLE
Confusion about the Dataset

### ISSUE THREAD

**Issue by TuGengs** [thu-coai/Emotional-Support-Conversation#32]
The meaning of "seeker_question1 and 2" as well as "supporter_question1 and 2" was not apparent in the paper. I kindly request the authors to provide an explanation for these terms for better clarity and understanding.

**Comment by chujiezheng** [comment]
@lsy641

**Comment by lsy641** [comment]
@TuGengs  They are Figure 8 (e) 
"is there anything you did or didn't like about the task?" 
"is there anything we can improve about our website and task?"
