### ISSUE TITLE
多轮对话评估问题

### ISSUE THREAD

**Issue by haidequanbu** [thu-coai/Emotional-Support-Conversation#36]
作者，您好，从大模型过来学习，之前没有做过传统模型的多轮对话的自动化指标评估，关于自动化评估有一些问题想请教，如果冒昧，还请海涵！
想请问下论文中多轮对话这些指标是怎么计算的？ppl比较好理解，Rouge、bleu等指标是怎么计算得到的呢？按照计算来看应该是有模型生成的多轮对话与和ground truth的多轮对话比较，第一轮对话的生成比较好理解，后几轮的对话模型是如何生成的呢？
<img width="416" alt="image" src="https://github.com/thu-coai/Emotional-Support-Conversation/assets/67882439/8d6c3e9a-d6f8-42da-a3b3-81f05d618991">

**Comment by chujiezheng** [comment]
后续轮次的回复是把前几轮的ground truth对话历史输入给模型生成的。

**Comment by haidequanbu** [comment]
理解了，感谢回复！

**Comment by SHIVAM3052** [comment]
> The responses in subsequent rounds are generated by inputting the ground truth conversation history of the previous rounds into the model.

Can you help me out how you are calculating bleu, rogue score in training
