### ISSUE TITLE
Confusion about FailedESConv

### ISSUE THREAD

**Issue by 43zxj** [thu-coai/Emotional-Support-Conversation#37]
根据您设置的有效负例的筛选条件，似乎situation为“I broke up with my girlfriend and i felt alone.What i can do that help me and cheer myself up?”的对话并不符合，想问一下您这个对话case是为何作为负例筛选出的呢？
![image](https://github.com/thu-coai/Emotional-Support-Conversation/assets/22003109/9fd26ea4-3f6f-4000-b34e-ce2f0415c03f)

**Comment by chujiezheng** [comment]
@lsy641

**Comment by lsy641** [comment]
Sorry. I failed to process an "else" condition when encountering the dialogs where emotion intensity is decreased and the empathy/relevance score is greater than 3. I will update the file soon
@43zxj
