### ISSUE TITLE
train

### ISSUE THREAD

**Issue by xiao-ming-code** [thu-coai/Emotional-Support-Conversation#4]
您好，在执行train_vanilla.sh步骤时出现的错误，前面都是按照redome进行操作，能麻烦进行解答一下么
![DXTO1D@ U_RZ5H6C@}YZ`MM](https://user-images.githubusercontent.com/73177290/127770812-c5f8e696-e47e-45db-bfd1-ec71acd81fec.png)

**Comment by chujiezheng** [comment]
我也看不懂你的错误信息，没有碰到过。可能是文件问题

**Comment by xiao-ming-code** [comment]
![XSIVUA%H9K9)3FH%J7XMD A](https://user-images.githubusercontent.com/73177290/127772287-7f4880f6-dc0e-4399-8e24-c8c339bace58.png)
![9M_042XEJN463_W RA3Y6C8](https://user-images.githubusercontent.com/73177290/127772290-91f36dd9-bc9d-40da-b557-652ac61cc400.png)
在infer的时候出现这个呢，能麻烦看看么 ，是环境问题么

**Comment by xiao-ming-code** [comment]
![1627869710(1)](https://user-images.githubusercontent.com/73177290/127794872-6cf76ada-70b6-4a46-bea2-08aac8ade8d6.png)
![1627869810(1)](https://user-images.githubusercontent.com/73177290/127794958-afbfa8f7-a1b2-4762-bd82-51629f2dbaa8.png) 在infer_vailla步骤出现这样的问题 能麻烦看一下么

**Comment by chujiezheng** [comment]
请提问之前自己看一下报错信息，你的报错信息已经显示没装java了
我的java版本是15.0.1

**Comment by xiao-ming-code** [comment]
![PJ1~VBR@8K6JUTGG5W3M%A2](https://user-images.githubusercontent.com/73177290/127942307-6f83c010-72cc-48bc-a3cf-6cf4e0de35ff.png)
麻烦了，就这个文件是有上传么，还是在运行中会生成 ，我在infer步骤报没有这个文件

**Comment by chujiezheng** [comment]
README和代码里面都有写，你可以仔细看一下
https://github.com/thu-coai/Emotional-Support-Conversation/tree/main/codes_zcj#downloading-model
https://github.com/thu-coai/Emotional-Support-Conversation/blob/05124288d2da898d66d57c52cf6ac8d408f367bf/codes_zcj/metric/word2vec/evaluate.py#L15
