### ISSUE TITLE
Emotional support

### ISSUE THREAD

**Issue by zzcceeyy** [thu-coai/Emotional-Support-Conversation#5]
![77HTI)`)4OR J$QXK3R@~HC](https://user-images.githubusercontent.com/88641930/133609810-079942e7-bcb2-4ee2-a335-a34aa7d63172.png)
Hello, could you please tell me the supported policy to reflect the position of the order (1->2->3) in the code?

**Comment by chujiezheng** [comment]
Hi, the orders are not reflected in the codes.

**Comment by lsy641** [comment]
ESC framework is used for training tutorials, which indicates supporters that providing support should follow a reasonable procedure. 
When we are doing this research,  a basic hypothesis is that we don't think we can achieve such a natural effect like now the simple-finetuning model in our paper does,  by just merely changing rules in codes, including forcibly coding order of 3-stage.
The highlight point is that we collected high-quality and real conversations that records how people arrange all strategies in their dialogs. It is a valuable resource for future research.
