### ISSUE TITLE
The training steps

### ISSUE THREAD

**Issue by zzcceeyy** [thu-coai/Emotional-Support-Conversation#6]
![)K7AXD0FA({}EM{NIUIKB(L](https://user-images.githubusercontent.com/88641930/133752796-6a36a9ce-cd22-4bdd-95a1-91a1fe9340a2.png)
在训练步骤这是会出现过拟合的问题么，可以解决么，

**Comment by chujiezheng** [comment]
inference时可以自己选checkpoint
