### ISSUE TITLE
About Backbone Models

### ISSUE THREAD

**Issue by LangDaoAI** [thu-coai/Emotional-Support-Conversation#9]
Hi, 

Great work ! 
I want to know whether CDial-GPT can be considered as one of the Backbone Models or not?

Thanks!

**Comment by chujiezheng** [comment]
CDial-GPT is a Chinese model. I think that it cannot be used in our English task :)

**Comment by LangDaoAI** [comment]
Thanks your reply!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
